; This file can be edited to change the style of the application
; Read "Qt Quick Controls 2 Configuration File" for details
; http://doc.qt.io/qt-5/qtquickcontrols2-configuration.html

[Controls]
Style=Material

[Material]
# Theme=Light
Variant=Dense

# Définition des couleurs du thème.
# Ici, il est inutile de les préfixer par "Material."

# Couleur des textes
# Foreground=Brown

# Couleur primaire = le bandeau de l'application. Les Chips
# Primary=Green

# Couleur d'accentuation pour les items en highlight.
# Accent=DeepOrange

# Couleur du fond: Barre de menu. Barre des onglets. Zones.
# Background=LightGreen



[Material\Font]
Family=Roboto
PointSize=11
