import QtQuick
import QtQuick.Layouts
import "../Components"

Item {
    width: 400
    property alias cameraZone: cameraZone
    property alias chipModel: chipModel
    property alias chipMaker: chipMaker
    property alias chipSoftware: chipSoftware
    property alias chipMetadata: chipMetadata
    property alias chipAperture: chipAperture
    property alias chipSpeed: chipSpeed
    property alias camThumb: camThumb

    Zone {
        id: cameraZone
        anchors.fill: parent
        iconZone: "qrc:/Images/icon-camera.png"
        txtZone: qsTr("Tags generated by the camera<br>at the moment of the shot.")

        ColumnLayout {
            Chips {
                id: chipModel
                editable: false
                deletable: false
                targetName: "model:"
            }
            Chips {
                id: chipMaker
                editable: false
                deletable: false
                targetName: "brand:"
            }
            Chips {
                id: chipSoftware
                editable: false
                deletable: false
                targetName: "software:"
            }
            Chips {
                id: chipMetadata
                editable: false
                deletable: false
            }
            Chips {
                id: chipAperture
                editable: false
                deletable: false
                targetName: "aperture:"
            }
            Chips {
                id: chipSpeed
                editable: false
                deletable: false
                targetName: "speed:"
            }
            Item {
                width: 128
                height: 128
                Layout.alignment: Qt.AlignHCenter
                Layout.bottomMargin: 10
                Image {
                    id: camThumb
                    height: 128
                    source: "../Cameras/default.png"
                    fillMode: Image.PreserveAspectFit
                }
            }
        }
    }
}
