theme: jekyll-theme-slate
title: ti Photo Locator
description: A desktop application to easily geotag your photos.
show_downloads: false

github:
  zip_url: https://github.com/Sphinkie/tiPhotoLocator/releases/latest/download/TiPhotoLocatorSetup.zip
  owner_name: David de Lorenzo
  owner_url: https://sphinkie.github.io/
